site_name: Tamil Cloud

theme:
  name: material
  palette:
    primary: red
    scheme: slate  # This ensures dark mode is always enabled
  logo: assets/image/tamil_cloud_logo.jpg
  favicon: assets/image/tamil_cloud_logo.jpg
  features:
    - navigation.instant
    - header.autohide
    - navigation.tabs

nav:
  - Home: index.md
  - AWS:
     - Linux Shell Scripting: aws/linuxeng-need-shell-scripting.md
     - Automatically Revert SG Rule: aws/automatically-revert-sg-rule.md  
  - DevOps Training 2024:
      - Index: devops_training/devops_trainng_2024.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tamil-cloud-%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D-%E0%AE%95%E0%AE%BF%E0%AE%B3%E0%AE%B5%E0%AF%81%E0%AE%9F%E0%AF%8D-41ab5519a
      name: LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@tamilcloudzone
      name: YouTube
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tamilcloudchennal
      name: Facebook

copyright: Copyright &copy; Tamil Cloud Commuity
